### ISSUE TITLE
Shopify Manifold Zip file error

### ISSUE THREAD

**Issue by deadformatmc** [manifoldxyz/manifold-templates#20]
The below error is occurring. Can we find a fix ?

zip does not contain a valid theme: missing template "layout/theme.liquid"
Upload a .zip file of your Shopify theme. Uploaded themes will be unpublished by default.

**Comment by wwhchung** [comment]
Which theme are you testing?

**Comment by deadformatmc** [comment]
Both come up with same error. But I am trying Dawn :)

**Comment by wwhchung** [comment]
I've just tested this with dawn and it seems to work.  Can you try downloading the zip again?

**Comment by wwhchung** [comment]
Note that you don't have to unzip things.

This is what I'm doing:
![image](https://user-images.githubusercontent.com/13840097/235981138-35bc868e-3e37-4176-8b74-78c76dfdce9a.png)

Upload zip file, select the zip.

**Comment by wwhchung** [comment]
That's really odd.  What OS/browser combo?  I can't seem to reproduce.

**Comment by deadformatmc** [comment]
ive sorted. it was messing up the download. re tried again. seems to be working now :) thanks for walking me through
